version: '2'
services:
    wliia-mongodb:
        container_name: wliia-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/wliia/mongodb/:/data/db/
